name: Build and Deploy WASM artifact

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: Build WASM
        run: |
          cargo build --release --target wasm32-unknown-unknown --features wasm

      - name: Rename artifact
        run: |
          ARTIFACT=target/wasm32-unknown-unknown/release/dprint_plugin_markdown.wasm
          UPLOAD=./dist/dprint_plugin_markdown-${{ github.ref_name }}.wasm
          mv ${ARTIFACT} ${UPLOAD}

      - name: Generate HTML
        run: ./scripts/build-page.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML and WASM artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${UPLOAD}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
